# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sketch/canvas.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(934, 654)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.identifyButton = QtWidgets.QPushButton(self.centralwidget)
        self.identifyButton.setObjectName("identifyButton")
        self.verticalLayout.addWidget(self.identifyButton)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setObjectName("clearButton")
        self.verticalLayout.addWidget(self.clearButton)
        self.eraseCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.eraseCheckBox.setObjectName("eraseCheckBox")
        self.verticalLayout.addWidget(self.eraseCheckBox)
        self.canvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.canvas.setObjectName("canvas")
        self.verticalLayout.addWidget(self.canvas)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.identifyButton.setText(_translate("MainWindow", "Identify"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.eraseCheckBox.setText(_translate("MainWindow", "Erase"))
